"""empty message

Revision ID: 0634633134b5
Revises: c9f39081b097
Create Date: 2021-01-20 18:43:28.273548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0634633134b5'
down_revision = 'c9f39081b097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    # ### end Alembic commands ###
