"""empty message

Revision ID: 3f8f655e5f2e
Revises: 7c5ea9914237
Create Date: 2021-01-31 16:44:04.060042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f8f655e5f2e'
down_revision = '7c5ea9914237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.String(length=200), nullable=True))
        batch_op.drop_column('img_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_path', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('file_name')

    # ### end Alembic commands ###
