"""empty message

Revision ID: 6de727cf7904
Revises: 2d17881a39c5
Create Date: 2021-02-13 15:07:56.235955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de727cf7904'
down_revision = '2d17881a39c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashtag_str', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hashtags'))
    )
    op.create_table('hashtag_post',
    sa.Column('hashtag_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], name=op.f('fk_hashtag_post_hashtag_id_hashtags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_hashtag_post_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hashtag_id', 'post_id', name=op.f('pk_hashtag_post'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hashtag_post')
    op.drop_table('hashtags')
    # ### end Alembic commands ###
