"""empty message

Revision ID: 7731aff4b6a2
Revises: cda7ab209e31
Create Date: 2021-01-27 16:04:28.345007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7731aff4b6a2'
down_revision = 'cda7ab209e31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('img_path',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('img_path',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
