"""empty message

Revision ID: 7c5ea9914237
Revises: b0425b89c93c
Create Date: 2021-01-29 18:12:56.228673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c5ea9914237'
down_revision = 'b0425b89c93c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], name=op.f('fk_follow_following_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_follow_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'following_id', name=op.f('pk_follow'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follow')
    # ### end Alembic commands ###
