"""empty message

Revision ID: c9f39081b097
Revises: d3123164254e
Create Date: 2021-01-20 18:42:46.478591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f39081b097'
down_revision = 'd3123164254e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', sa.Integer(), server_default='1', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###
